#!/bin/bash

# setup-lxc-failover.sh
# This script sets up the failover logic for LXC containers
# to switch between a primary and secondary gateway.
# It is designed to be idempotent.

set -e

# --- Configuration ---
# Load site-specific values from .env (not tracked in version control)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
    # shellcheck source=.env
    source "$SCRIPT_DIR/.env"
else
    echo "Error: .env file not found at $SCRIPT_DIR/.env"
    echo "Copy .env.example to .env and fill in your site-specific values."
    exit 1
fi

# Validate required variables are set
for var in IF_PRIMARY IF_SECONDARY GW_PRIMARY GW_SECONDARY TEST_IP REPO_OUTER_PATH REPO_INNER_PATH AUTO_UPDATE_LOG; do
    if [ -z "${!var}" ]; then
        echo "Error: Required variable $var is not set in .env"
        exit 1
    fi
done

# Log file for the failover script
LOG_FILE="/var/log/gateway-failover.log"

# --- Diagnostic Function ---
print_diagnostics() {
    echo ""
    echo "=== Network Interface Diagnostic Report ==="
    # Try to use 'ip -br' for a concise table, fallback to standard if not available
    if ip -br addr show >/dev/null 2>&1; then
        echo "Interface  Status  IP Addresses"
        echo "--------------------------------------------------"
        ip -br addr show
    else
        echo "Interface  IP Address"
        echo "--------------------------------------------------"
        ip addr show | grep 'inet ' | awk '{print $NF, $2}'
    fi
    echo "--------------------------------------------------"
    echo "Current Default Gateway:"
    ip route show default
    echo "=================================================="
    echo ""
}

# Run diagnostics at start
print_diagnostics

# --- Pre-flight Checks ---
echo "Running pre-flight checks..."

if ! ip link show "$IF_SECONDARY" >/dev/null 2>&1; then
    echo "Error: Secondary interface $IF_SECONDARY not found."
    exit 1
fi

if ! ip link show "$IF_PRIMARY" >/dev/null 2>&1; then
    echo "Error: Primary interface $IF_PRIMARY not found."
    exit 1
fi

# Check if IPs are assigned (rudimentary check)
if ! ip addr show "$IF_SECONDARY" | grep -q "inet"; then
    echo "Warning: No IPv4 address assigned to secondary interface $IF_SECONDARY."
fi

if ! ip addr show "$IF_PRIMARY" | grep -q "inet"; then
    echo "Warning: No IPv4 address assigned to primary interface $IF_PRIMARY."
fi

# Check for /dev/net/tun (required for Tailscale)
if [ ! -c /dev/net/tun ]; then
    echo "Warning: /dev/net/tun not found. Tailscale may fail."
    echo "Attempting to create /dev/net/tun..."
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200 2>/dev/null || true
    chmod 0666 /dev/net/tun 2>/dev/null || true
    
    if [ ! -c /dev/net/tun ]; then
        echo "Error: Failed to create /dev/net/tun. Please check LXC configuration (lxc.cgroup2.devices.allow, lxc.mount.entry)."
        exit 1
    fi
fi

echo "Pre-flight checks passed."

# --- Failover Script Creation & Execution (Early) ---
# We need to set up the gateway BEFORE trying to install packages.

echo "Creating failover script..."
FAILOVER_SCRIPT="/usr/local/bin/gateway-failover.sh"

cat > "$FAILOVER_SCRIPT" <<EOF
#!/bin/bash
# Gateway Failover Script
# Generated by setup-lxc-failover.sh

IF_PRIMARY="$IF_PRIMARY"
IF_SECONDARY="$IF_SECONDARY"
GW_PRIMARY="$GW_PRIMARY"
GW_SECONDARY="$GW_SECONDARY"
TEST_IP="$TEST_IP"
LOG_FILE="$LOG_FILE"

log() {
    echo "\$(date): \$1" >> "\$LOG_FILE"
}

check_connection() {
    local gw=\$1
    local iface=\$2
    
    # Add a specific route to the test IP via the gateway
    ip route add "\$TEST_IP" via "\$gw" dev "\$iface" 2>/dev/null
    
    # Ping with timeout
    if ping -c 1 -W 2 "\$TEST_IP" >/dev/null 2>&1; then
        # Success
        ip route del "\$TEST_IP" via "\$gw" dev "\$iface" 2>/dev/null
        return 0
    else
        # Failure
        ip route del "\$TEST_IP" via "\$gw" dev "\$iface" 2>/dev/null
        return 1
    fi
}

current_gw=\$(ip route show default | awk '{print \$3}')

# Strategy: Prefer primary gateway.
# 1. Check primary.
# 2. If primary up, ensure primary is default.
# 3. If primary down, check secondary.
# 4. If secondary up, ensure secondary is default.

if check_connection "\$GW_PRIMARY" "\$IF_PRIMARY"; then
    # Primary is UP
    if [ "\$current_gw" != "\$GW_PRIMARY" ]; then
        log "Switching to Primary Gateway (\$GW_PRIMARY)"
        ip route replace default via "\$GW_PRIMARY" dev "\$IF_PRIMARY"
    fi
else
    # Primary is DOWN
    log "Primary Gateway is unreachable."
    
    if check_connection "\$GW_SECONDARY" "\$IF_SECONDARY"; then
        # Secondary is UP
        if [ "\$current_gw" != "\$GW_SECONDARY" ]; then
            log "Switching to Secondary Gateway (\$GW_SECONDARY)"
            ip route replace default via "\$GW_SECONDARY" dev "\$IF_SECONDARY"
        fi
    else
        # Both DOWN
        log "CRITICAL: Both gateways are unreachable."
    fi
fi
EOF

chmod +x "$FAILOVER_SCRIPT"

echo "Running failover script to establish connectivity..."
$FAILOVER_SCRIPT
echo "Connectivity check complete."

# --- System Setup (Idempotent) ---
echo "Configuring system..."

# 1. Install dependencies
# Update only if we haven't recently (optional, but good for idempotency speed)
if [ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60 2>/dev/null)" ]; then
    apt-get update
fi

DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    git \
    iptables \
    iptables-persistent \
    iproute2 \
    iputils-ping \
    netfilter-persistent \
    tcpdump

# 2. Enable IP Forwarding (Tailscale requirement)
echo "Configuring sysctl..."
cat > /etc/sysctl.d/99-tailscale.conf <<EOF
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
EOF
sysctl -p /etc/sysctl.d/99-tailscale.conf

# 3. Configure Masquerading (if needed for exit node functionality)
# If this node is an exit node, it needs to masquerade traffic leaving the WAN interfaces.
# We also masquerade on eth0 (internal) because Tailscale/Headscale may route DNS
# through the internal subnet.
# We will ensure masquerade is on for all relevant interfaces.
echo "Configuring iptables..."
if ! iptables -t nat -C POSTROUTING -o "$IF_SECONDARY" -j MASQUERADE 2>/dev/null; then
    iptables -t nat -A POSTROUTING -o "$IF_SECONDARY" -j MASQUERADE
fi
if ! iptables -t nat -C POSTROUTING -o "$IF_PRIMARY" -j MASQUERADE 2>/dev/null; then
    iptables -t nat -A POSTROUTING -o "$IF_PRIMARY" -j MASQUERADE
fi
# Also eth0 (internal network) as per README example, though usually masquerade is for WAN.
# Tailscale/Headscale may route DNS via an internal subnet on eth0.
if ! iptables -t nat -C POSTROUTING -o eth0 -j MASQUERADE 2>/dev/null; then
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
fi

# 3b. Fix MTU/Fragmentation issues for Tailscale clients (MSS Clamping)
# Tailscale adds overhead to packets. If a packet is already at MTU (1500),
# the extra overhead causes fragmentation or drops.
# This rule clamps the TCP MSS (Maximum Segment Size) to the Path MTU,
# ensuring packets fit inside the tunnel.
#
# If you see "Unable to connect to coordination server" warnings on clients:
# 1. Ensure this rule is active.
# 2. Toggle Airplane Mode on the client for 5s to force a fresh connection.
echo "Configuring MSS clamping..."
if ! iptables -t mangle -C FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu 2>/dev/null; then
    iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
fi

netfilter-persistent save

# 4. Install Tailscale (if not present)
if ! command -v tailscale >/dev/null 2>&1; then
    echo "Installing Tailscale..."
    curl -fsSL https://tailscale.com/install.sh | sh
else
    echo "Tailscale is already installed."
fi

# --- SSH / Git Setup ---
SSH_GIT_SETUP="$SCRIPT_DIR/setup-ssh-and-git.sh"
if [ -f "$SSH_GIT_SETUP" ]; then
    echo "Running SSH and git setup..."
    bash "$SSH_GIT_SETUP"
else
    echo "Warning: $SSH_GIT_SETUP not found — automated git pulls will not work until SSH is configured."
fi

# --- Auto-update Script ---
AUTO_UPDATE_SCRIPT="/usr/local/bin/auto-update.sh"
REPO_OUTER_PATH="${REPO_OUTER_PATH}"
REPO_INNER_PATH="${REPO_INNER_PATH}"
GIT_TIMEOUT_VAL="${GIT_TIMEOUT:-5}"
AUTO_UPDATE_LOG_FILE="${AUTO_UPDATE_LOG}"

echo "Creating auto-update script..."
cat > "$AUTO_UPDATE_SCRIPT" <<EOF
#!/bin/bash
# auto-update.sh — deployed by setup-lxc-failover.sh
# Pulls latest config from git repos with a hard timeout.
# Values were baked in at deploy time from .env — re-run setup to change them.

REPO_OUTER_PATH="$REPO_OUTER_PATH"
REPO_INNER_PATH="$REPO_INNER_PATH"
GIT_TIMEOUT="$GIT_TIMEOUT_VAL"
LOG_FILE="$AUTO_UPDATE_LOG_FILE"

log() {
    echo "\$(date): \$1" >> "\$LOG_FILE"
}

pull_repo() {
    local name="\$1"
    local path="\$2"

    [ -z "\$path" ] && return

    if [ ! -d "\$path/.git" ]; then
        log "[\$name] Not a git repo at \$path — skipping."
        return
    fi

    local output exit_code
    output=\$(timeout "\$GIT_TIMEOUT" git -C "\$path" pull --ff-only 2>&1)
    exit_code=\$?

    if [ "\$exit_code" -eq 124 ]; then
        log "[\$name] Timed out after \${GIT_TIMEOUT}s — continuing."
    elif [ "\$exit_code" -ne 0 ]; then
        log "[\$name] Pull failed (exit \$exit_code): \$output — continuing."
    else
        log "[\$name] \$output"
    fi
}

log "=== Auto-update started ==="

# Wait for network with a short retry loop — LXC containers can reach
# network-online.target before interfaces are fully ready.
for attempt in 1 2 3 4 5 6 7 8 9 10; do
    if ping -c 1 -W 2 8.8.8.8 >/dev/null 2>&1; then
        break
    fi
    log "[network] Not ready, waiting 5s (attempt \$attempt/10)..."
    sleep 5
done

pull_repo "outer-repo" "\$REPO_OUTER_PATH"
pull_repo "inner-repo" "\$REPO_INNER_PATH"
log "=== Auto-update complete ==="
EOF

chmod +x "$AUTO_UPDATE_SCRIPT"
echo "Auto-update script created."

# --- Cron Job Setup ---
echo "Setting up cron job..."
CRON_FILE="/etc/cron.d/gateway-failover"
cat > "$CRON_FILE" <<EOF
* * * * * root $FAILOVER_SCRIPT
EOF

# --- Systemd Boot Service for Auto-update ---
# Pulls latest config on startup, then exits. Not a recurring job.
echo "Installing auto-update boot service..."
cat > /etc/systemd/system/auto-update.service <<EOF
[Unit]
Description=Pull latest config from git repos on boot
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=$AUTO_UPDATE_SCRIPT
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable auto-update.service
echo "Auto-update boot service installed and enabled."

# --- Finalize ---
echo "Setup complete."
echo "Done. Check $LOG_FILE for status."

# --- Diagnostic Report ---
print_diagnostics
